# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-07 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityName', models.CharField(blank=True, max_length=120, null=True)),
                ('activityStandardTime', models.IntegerField(default=0)),
                ('activityTime', models.IntegerField(default=0)),
                ('step', models.IntegerField(default=10)),
                ('assignedTo', models.CharField(blank=True, max_length=30, null=True)),
                ('assignedOrder', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workOrder', models.CharField(blank=True, max_length=25)),
                ('workTime', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignedToPR', models.CharField(blank=True, max_length=30, null=True)),
                ('repairActivities', models.ManyToManyField(to='production.Activity')),
            ],
        ),
        migrations.AddField(
            model_name='bom',
            name='repairRoute',
            field=models.ManyToManyField(to='production.ProcessRoute'),
        ),
    ]
