# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-15 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
                ('lastName', models.CharField(blank=True, max_length=80, null=True)),
                ('employeeNumber', models.IntegerField(default=0)),
                ('salary', models.IntegerField(default=0)),
                ('admission', models.DateField()),
            ],
        ),
    ]
