# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-05 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryCatalogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20)),
                ('category_number', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'CategoriesCatalogue',
            },
        ),
        migrations.CreateModel(
            name='ContactRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True, max_length=30, null=True)),
                ('mensaje', models.TextField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='OrderCatalogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProductRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=35, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=120, null=True)),
                ('cantidad_minima', models.IntegerField(default=0)),
                ('cantidad_maxima', models.IntegerField(default=0)),
                ('punto_reorden', models.IntegerField(default=0)),
                ('proveedor', models.CharField(blank=True, max_length=30, null=True)),
                ('categoria', models.CharField(default='Default', max_length=20)),
                ('sku', models.CharField(blank=True, default='NA', max_length=25)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/images')),
                ('ubicacion', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_ingreso', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ProviderRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=120, null=True)),
                ('rfc', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(max_length=120)),
                ('productos', models.CharField(max_length=120)),
                ('cantidad', models.IntegerField()),
                ('punto_reorden', models.IntegerField(default=0)),
            ],
        ),
    ]
