# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=35, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=120, null=True)),
                ('cantidad', models.IntegerField()),
                ('ubicacion', models.CharField(blank=True, max_length=10, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=10, null=True)),
                ('fechaIngreso', models.DateField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
