# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-20 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=120, null=True)),
                ('rfc', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(max_length=120)),
                ('productos', models.CharField(max_length=120)),
                ('cantidad', models.IntegerField()),
                ('punto_reorden', models.IntegerField()),
            ],
        ),
    ]
