# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-05 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20181005_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorycatalogue',
            name='category_status',
            field=models.CharField(default='ACTIVE', max_length=10),
        ),
    ]
