# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-02 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productprovider'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True, max_length=30, null=True)),
                ('mensaje', models.TextField(blank=True, max_length=100, null=True)),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
    ]
