# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-05 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_categorycatalogue_category_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorycatalogue',
            name='category_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='categorycatalogue',
            name='category_number',
            field=models.CharField(max_length=5),
        ),
    ]
