# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-02 23:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20180802_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='productregister',
            name='cantidad_minima',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productregister',
            name='reorden',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
