# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-02 23:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20180802_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productregister',
            name='cantidad_minima',
        ),
        migrations.RemoveField(
            model_name='productregister',
            name='reorden',
        ),
    ]
