# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-02 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20180802_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='productregister',
            name='cantidad_minima',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productregister',
            name='punto_reorden',
            field=models.IntegerField(default=0),
        ),
    ]
