# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-02 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20180802_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprovider',
            name='punto_reorden',
            field=models.IntegerField(default=0),
        ),
    ]
