# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-16 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20180815_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='productregister',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
