# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-09-07 19:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='creationDate',
            field=models.DateField(default=datetime.datetime(2018, 9, 7, 19, 25, 7, 314223)),
        ),
    ]
