# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-09-07 19:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_auto_20180907_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='creationDate',
            field=models.DateField(default=datetime.datetime(2018, 9, 7, 19, 25, 31, 364676)),
        ),
        migrations.AlterField(
            model_name='quote',
            name='deliveryDate',
            field=models.DateField(default=datetime.datetime(2018, 9, 7, 19, 25, 31, 364907)),
        ),
    ]
